# -*- coding: utf-8 -*-
"""Inquilinos_Retos_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRkEHiYT6jqu5kj93DOsNx132zq1EFQg

#
 Inquilinos — RETOS (EDA + Modelado + Informe en el mismo Colab)
"""

#RETO 0.0 — Librerías
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
from IPython.display import Markdown, display
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
plt.rcParams.update({"figure.autolayout": True})

inquilinos = pd.read_csv("/dataset/ds_inquilinos.csv")

#RETO 1.2 — Vista rápida
inquilinos.head(10)

#RETO 1.3 — Info columnas
inquilinos.info()

#RETO 1.4 — Descriptivo categorías
inquilinos.describe(include=['object'])

#RETO 1.5 — Histograma global (columnas numéricas)
inquilinos.hist(bins=30, figsize=(10, 8))
plt.show()

#RETO 1.6 — Nulos por columna
inquilinos.isnull().sum()

#RETO 1.9 — Conteos por columna (excepto id)
for col in inquilinos.drop('id_inquilino', axis=1, errors='ignore').columns:
    print("--- {} ---".format(col))
    print(inquilinos[col].value_counts())
    print()

#RETO 1.10 — Pie de nivel educativo
plt.figure(figsize=(6, 4))
nivel_counts = inquilinos['nivel_educativo'].value_counts()
plt.pie(nivel_counts.values, labels=nivel_counts.index.tolist(), autopct='%1.1f%%')
plt.title('Distribución Nivel Educativo')
plt.show()

#RETO 1.11 — Barras de ritmo
plt.figure(figsize=(6, 4))
rcount = inquilinos['ritmo'].value_counts()
plt.bar(rcount.index, rcount.values)
plt.title('Distribución de ritmos')
plt.xlabel('ritmo')
plt.ylabel('Número de inquilinos')
plt.xticks(ticks=range(len(rcount.index)), labels=['Madrugador','Nocturno'])
plt.show()

#RETO 2.0 — Copia y mapeos binarios (preprocesamiento)
df = inquilinos.copy()
for c in ['id_inquilino', 'musica_tipo', 'nivel_educativo', 'instrumento']:
    if c in df.columns:
        df.drop(c, axis=1, inplace=True)
binarias = {
    'animacion': {'si': 1, 'no': 0},
    'cine': {'si': 1, 'no': 0},
    'leer': {'si': 1, 'no': 0},
    'deporte': {'si': 1, 'no': 0},
    'dieta': {'si': 1, 'no': 0},
    'fumador': {'si': 1, 'no': 0},
    'visitas': {'si': 1, 'no': 0},
    'musica_alta': {'si': 1, 'no': 0},
    'mascotas': {'con mascotas': 1, 'sin mascotas': 0},
    'comida': {'pedir comida': 0, 'cocinar': 1},
    'orden': {'relajada': 0, 'ordenada': 1},
    'plan_perfecto': {'casa': 0, 'salir': 1},
    'ritmo': {'madrugador': 1, 'nocturno': 0},
    'horario': {'mañana': 1, 'noche': 0}
}
for col, mapping in binarias.items():
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.lower().map(mapping)

#RETO 2.1 — Split + modelos
TARGET = 'ritmo'
assert TARGET in df.columns, 'No existe la columna {}'.format(TARGET)
X = df.drop(TARGET, axis=1).select_dtypes(include=[np.number])
y = df[TARGET]

X.isna().sum()[lambda s: s>0]


from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='most_frequent')
X = pd.DataFrame(imp.fit_transform(X), columns=X.columns)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)
modelos = {
    'DecisionTree': DecisionTreeClassifier(random_state=42),
    'RandomForest': RandomForestClassifier(n_estimators=200, random_state=42),
    'KNN': KNeighborsClassifier(n_neighbors=7)
}
metricas = {}
for name, model in modelos.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    pre = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    rec = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1  = f1_score(y_test, y_pred, average='weighted', zero_division=0)
    metricas[name] = {'accuracy': acc, 'precision': pre, 'recall': rec, 'f1': f1}
metricas

#RETO 2.2 — Mejor modelo + Reporte + Matriz de Confusión
best_name = max(metricas, key=lambda k: metricas[k]['accuracy'])
best_model = modelos[best_name]
y_pred = best_model.predict(X_test)
print('Mejor modelo:', best_name, '\n')
print(classification_report(y_test, y_pred, zero_division=0))
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(4.8, 4.2))
plt.imshow(cm, aspect='auto')
plt.title('Matriz de Confusión')
plt.xlabel('Predicciones')
plt.ylabel('Reales')
plt.colorbar()
for (i, j), val in np.ndenumerate(cm):
    plt.text(j, i, str(val), ha='center', va='center')
plt.tight_layout()
plt.savefig('cm_actual.png', dpi=120, bbox_inches='tight')
plt.show()

#RETO 2.3 — Importancia de variables (si aplica)
try:
    importancias = best_model.feature_importances_
    idx = np.argsort(importancias)[::-1][:15]
    plt.figure(figsize=(6, 5))
    plt.barh(range(len(idx)), importancias[idx])
    plt.yticks(range(len(idx)), X.columns[idx])
    plt.gca().invert_yaxis()
    plt.title('Importancia de características (Top 15) — {}'.format(best_name))
    plt.tight_layout()
    plt.savefig('fi_actual.png', dpi=120, bbox_inches='tight')
    plt.show()
except Exception as e:
    print('El modelo seleccionado no soporta importancias:', e)
    importancias = None

#RETO 3.0 — Informe Markdown dentro del mismo notebook
acc = metricas[best_name]['accuracy']
pre = metricas[best_name]['precision']
rec = metricas[best_name]['recall']
f1  = metricas[best_name]['f1']

tabla = (
    "| Métrica | Valor |\n|---|---:|\n"
    + "| Accuracy | {:.3f} |\n".format(acc)
    + "| Precision (weighted) | {:.3f} |\n".format(pre)
    + "| Recall (weighted) | {:.3f} |\n".format(rec)
    + "| F1 (weighted) | {:.3f} |".format(f1)
)

imp_md = ""
if 'importancias' in locals() and importancias is not None:
    pares = [(X.columns[i], float(importancias[i])) for i in idx]
    filas = "\n".join(["| {} | {:.4f} |".format(n, v) for n, v in pares])
    imp_md = (
        "\n\n**Importancia de características (Top 15)**\n\n"
        + "| Variable | Importancia |\n|---|---:|\n" + filas
    )

md = (
    "# Informe — Dataset de Inquilinos\n\n"
    + "**Archivo:** `{}`  \\n".format(inquilinos)
    + "**Objetivo:** `{}`  \\n".format(TARGET)
    + "**Mejor modelo:** `{}`\n\n".format(best_name)
    + "## 1) EDA breve\n"
    + "- Columnas categóricas principales exploradas (conteos y distribuciones).\n"
    + "- Gráficas: Nivel educativo (pie), Ritmo (barras).\n"
    + "- Revisar nulos y valores únicos en las celdas previas.\n\n"
    + "## 2) Preprocesamiento\n"
    + "- Mapeos binarios de texto → 0/1 (si/no, con/sin, madrugador/nocturno, etc.).\n"
    + "- Columnas textuales no usadas removidas: `id_inquilino`, `musica_tipo`, `nivel_educativo`, `instrumento`.\n\n"
    + "## 3) Modelado\n"
    + "- Train/Test split (estratificado, 10% test).\n"
    + "- Modelos comparados: DecisionTree, RandomForest, KNN.\n"
    + "- Selección por accuracy en test.\n\n"
    + "## 4) Métricas (Test)\n"
    + tabla + "\n\n"
    + "### Matriz de confusión\n"
    + "![cm](cm_actual.png)\n\n"
    + imp_md + "\n\n"
    + "## 5) Conclusiones\n"
    + "- El modelo `{}` obtiene accuracy ~ {:.2%} en este split.\n".format(best_name, acc)
    + "- Recomendado: ajustar hiperparámetros, revisar desbalance y evaluar ROC/PR.\n"
    + "- Probar otros objetivos (`fumador`, etc.) repitiendo las celdas de modelado.\n"
)

display(Markdown(md))
with open("Informe_Colab.md", "w", encoding="utf-8") as f:
    f.write(md)

